### ISSUE TITLE
enalerte.ca données / MSP 

### ISSUE THREAD

**Issue by MivraMe** [domo-quebec/domo-quebec#20]
Je ne sais pas à quoi pourrait servir les données pour le moment, mais EN ALERTE m'a envoyé les liens suivants :

RSS : http://rss.naad-adna.pelmorex.com/
Socket TCP : http://streaming.naad-adna.pelmorex.com:8080/ 

Je ne peux pas upload le xml et les fichiers bruno ici :(

**Comment by mdallaire** [comment]
Ça ressemble beaucoup à https://geoegl.msp.gouv.qc.ca/avp/rss/ qui est le feed du ministère de la sécurité publique.

As-tu essayé le script dans la section MSP? https://github.com/domo-quebec/domo-quebec/blob/main/msp/msp-parser.py

Ça fait un petit bout que je n'y ai pas touché mais je pense que ça devrait encore fonctionné. Si tu as le gout de l'améliorer ou de faire les configs pour Home-Assistant ça peut être un bon point de départ!

**Comment by MivraMe** [comment]
Je regarde, merci !
